# Copy this file to a repository and edit it as needed to set up the reusable workflow
name: "Build, Scan container image"

on:
  push:
    branches:
      - 'main'
# Cancel any active runs of this workflow for the same branch
# concurrency:
  # group: ${{ github.ref }}-${{ github.workflow }}
  # cancel-in-progress: true

permissions: read-all

jobs:
  invoke-reusable-build:
    strategy:
      matrix:
        docker-file:
          - './service1/Dockerfile'
          - './service2/Dockerfile'
    name: "Invoke reusable build workflow"
    uses: <your-org>/<your-repo>/.github/workflows/reusable-build-provider.yaml@<branch>
    # Invoking permissions must be equal to or greater than those for the reusable workflow provider
    # Permisions set here for the GITHUB_TOKEN will be passed on to callee
    permissions:
      actions: read
      contents: read
      security-events: write
      # to push docker image to ghcr.io
      # packages: write
      # to create, update comments in PRs
      # pull-requests: write
    with:
      # Check '.on.workflow_call.inputs' of the workflow provider
      docker-file: ${{ matrix.docker-file }}
      severity: "CRITICAL,HIGH"
