name: "Reusable workflow to build with docker and scan with trivy"

on:
  workflow_call:
    inputs:
      docker-file:
        required: false
        type: string
        default: "./Dockerfile"
      severity:
        required: false
        type: string
        default: "CRITICAL,HIGH"
      output:
        required: false
        type: string
        default: 'trivy-results-${{ github.repository }}.sarif'
      hide-progress:
        required: false
        type: boolean
        default: false
permissions:
  actions: read
  contents: read
  security-events: write
  # to push docker image to ghcr.io
  # packages: write
  # to create, update comments in PRs
  # pull-requests: write

jobs:
  build-scan:
    name: "build, scan"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Prepare image reference
        run: |
          echo "GH_REPOSITORY=$(echo ${{ github.repository }} | cut -d '/' -f2 )" >> $GITHUB_ENV
      - name: Build Image
        run: |
          docker build -t $GH_REPOSITORY:${{ github.sha }} -f ${{ inputs.docker-file }}
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "${{ env.GH_REPOSITORY }}:${{ github.sha }}"
          exit-code: "1"
          hide-progress: ${{ inputs.progress }}
          format: "sarif"
          severity: ${{ inputs.severity }}
          output: ${{ inputs.output }}
      - name: Upload Trivy scan results to GH Advanced Security
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ inputs.output }}
